WIP License header of files
flyve-mdm/flyve-mdm-glpi-demo pull request #29
Opened 2018-01-30 20:15 UTC by Naylin15

### Changes description
The license header of the project files was changed
* the Copyright date was changed to 2018
* The complete name of the project license was added in the main description
* Links were updated

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [x] Docs have been added/updated

### References

Closes #19

2018-02-07 23:17 UTC, ajsb85 approved these changes

2018-02-07 23:19 UTC, ajsb85 requested changes
Hi, @Naylin15 
Looks good to me, but the copyright started from 2017. 
So, add the 2017-2018 range.
Thanks.

2018-02-08 12:47 UTC, Naylin15 commented
Ok, I'm making the correction

2018-02-08 15:09 UTC, ajsb85 approved these changes

2018-02-08 15:09 UTC, merged